vim.opt.cmdheight = 2 -- more space in the neovim command line for displaying messages
vim.opt.conceallevel = 0 -- so that `` is visible in markdown files
--vim.opt.fileencoding = "utf-8"
vim.opt.ignorecase = true -- ignore case in search patterns
vim.opt.termguicolors = true
vim.opt.expandtab = true -- convert tabs to spaces
vim.opt.shiftwidth = 2 -- the number of spaces inserted for each indentation
vim.opt.tabstop = 2 -- insert 2 spaces for a tab
vim.opt.cursorline = true -- highlight the current line
vim.opt.number = true -- set numbered lines
vim.opt.relativenumber = true -- set relative numbered lines
vim.opt.wrap = false -- display lines as one long line
vim.opt.showmode = false -- we don't need to see things like -- INSERT -- anymore
